# This workflow will perform a compilation test on 
# each push to the branch master to check its correct 
# compilation and will deliver an artifact to check 
# if the change is working properly.
name: FlameCord Build (master)

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    # The corresponding tests are performed in the versions
    # marked as Long Term Support by Oracle and in its
    # latest version up to the moment.
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
    # Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: 2lstudios-mc/FlameCord
        submodules: true

    # Setup a version of the Java JDK
    - name: Setup JAVA ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Setup build dependencies
      run: |
        sudo apt update
        sudo apt install -y maven

    # The corresponding dependencies are stored in the cache to speed up the test.
    - name: Cache Maven Packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Remove bad limit
      run: |
        cd Waterfall-Proxy-Patches
        sed -i '/private Collection<String> antibotCountryBlacklist/c +private Collection<String> antibotCountryBlacklist = new ArrayList<String>();' 00??-Antibot-System.patch

    # Start building FlameCord
    - name: Build FlameCord
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'actions@github.com'
        scripts/build.sh --jar

    # An artifact is generated in a compressed file according to each JDK build version.
    - name: Upload FlameCord
      uses: actions/upload-artifact@v3
      with:
        name: FlameCord-JDK${{ matrix.java }}
        path: FlameCord-Proxy/bootstrap/target/FlameCord.jar
